### ISSUE TITLE
2.2.4 Crashes on Android

### ISSUE THREAD

**Issue by Burstaholic** [RocketChat/Rocket.Chat.Cordova#87]
adb logcat:

```
03-29 22:37:04.823  3124  3124 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-29 22:37:04.823  3124  3124 E AndroidRuntime: FATAL EXCEPTION: main
03-29 22:37:04.823  3124  3124 E AndroidRuntime: Process: com.konecty.rocket.chat, PID: 3124
03-29 22:37:04.823  3124  3124 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.konecty.rocket.chat/com.konecty.rocket.chat.MainActivity}: java.lang.NumberFormatException: Invalid long: ".2"
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-29 22:37:04.823  3124  3124 E AndroidRuntime: Caused by: java.lang.NumberFormatException: Invalid long: ".2"
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at java.lang.Long.invalidLong(Long.java:124)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at java.lang.Long.parse(Long.java:363)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at java.lang.Long.decode(Long.java:177)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.CordovaPreferences.getInteger(CordovaPreferences.java:78)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.splashscreen.SplashScreen.getFadeDuration(SplashScreen.java:120)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.splashscreen.SplashScreen.showSplashScreen(SplashScreen.java:261)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.splashscreen.SplashScreen.pluginInitialize(SplashScreen.java:103)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.PluginManager.init(PluginManager.java:87)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at com.konecty.rocket.chat.MainActivity.onCreate(MainActivity.java:32)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
03-29 22:37:04.823  3124  3124 E AndroidRuntime:        ... 9 more
03-29 22:37:04.823  1308  1553 W ActivityManager:   Force finishing activity com.konecty.rocket.chat/.MainActivity
```

I'd debug this more, but apparently Gradle and Android Studio aren't getting along right now, and therapy will have to be later.

**Comment by rodrigok** [comment]
The beta was fixed, can you test with the latest?

**Comment by Burstaholic** [comment]
Just to document, it looks like the `.2` value in the `FadeSplashScreenDuration` was the issue, and removing that did fix the crash for me.
